### ISSUE TITLE
Procedure

### ISSUE THREAD

**Issue by doxmeifucan** [Jayapraveen/Guvi-courses-downloader#1]
.

**Comment by Jayapraveen** [comment]
Hello @aaahimel ,
The script will dump the server output of each video location for the courses you have enrolled. Since downloading the video itself will classify the script with malicious intent. You'll have to further modify the script to download the videos or parse the dump to extract the video urls.
As of Execution,
1. Enter you credentials inside the login function between the empty quotes, first email and inside the second empty quote Password .
2. Run the script like a normal one. 
3. Wait till the script completes downloading all the courses dump you have enrolled for.
